# Generated by Django 3.2.10 on 2021-12-10 12:53

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datation',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            managers=[
                ('h_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('datation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topicModule.datation')),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_topic_related', related_query_name='social_topics', to='social.profil')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
                'ordering': ['created', 'title'],
            },
            bases=('topicModule.datation',),
            managers=[
                ('h_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfilTopic',
            fields=[
                ('datation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topicModule.datation')),
                ('reason', models.TextField(max_length=500)),
                ('suscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_usertopic_related', related_query_name='social_usertopics', to='social.profil')),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topicModule_usertopic_related', related_query_name='topicModule_usertopics', to='topicModule.topic')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('topicModule.datation',),
            managers=[
                ('h_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
