# Generated by Django 3.2.9 on 2021-12-02 18:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_topic_related', related_query_name='social_topics', to='social.profil')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
                'ordering': ['created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.TextField(max_length=500)),
                ('last_opened', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('end', models.DateField(null=True)),
                ('suscribers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_usertopic_related', related_query_name='social_usertopics', to='social.profil')),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicModule_usertopic_related', related_query_name='topicModule_usertopics', to='topicModule.topic')),
            ],
        ),
    ]
