# Generated by Django 3.2.9 on 2021-12-02 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('media', models.FileField(blank=True, null=True, upload_to='static/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': 'contents',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
