# Generated by Django 3.2.10 on 2021-12-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commentModule', '0001_initial'),
        ('postModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postModule_comment_related', related_query_name='postModule_comments', to='postModule.post'),
        ),
    ]
