# Generated by Django 3.2.9 on 2021-12-07 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentModule', '0003_comment_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
