# Generated by Django 3.2.10 on 2021-12-10 12:53

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datation',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            managers=[
                ('h_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('datation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groupModule.datation')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('visibilty', models.CharField(choices=[('PUG', 'Public Group'), ('PRG', 'Private Group')], max_length=100)),
                ('link', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['created', 'name'],
            },
            bases=('groupModule.datation',),
            managers=[
                ('h_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('datation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groupModule.datation')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groupModule_member_related', related_query_name='groupModule_members', to='groupModule.community')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['created', 'is_admin', 'is_owner'],
            },
            bases=('groupModule.datation',),
            managers=[
                ('h_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
