# Generated by Django 3.2.9 on 2021-12-02 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupModule', '0001_initial'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_member_related', related_query_name='social_members', to='social.profil'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='social_group_related', related_query_name='social_groups', through='groupModule.Member', to='social.Profil'),
        ),
    ]
