# Generated by Django 3.2.9 on 2021-12-02 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
        ('postModule', '0001_initial'),
        ('topicModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_share_related', related_query_name='social_shares', to='social.profil'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='social_likes_related', related_query_name='socials_likecontents', through='postModule.Like', to='social.Profil'),
        ),
        migrations.AddField(
            model_name='post',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_content_related', related_query_name='social_contents', to='social.profil'),
        ),
        migrations.AddField(
            model_name='post',
            name='shares',
            field=models.ManyToManyField(related_name='social_post_related', related_query_name='social_posts', through='postModule.Share', to='social.Profil'),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicModule_post_related', related_query_name='topicModule_posts', to='topicModule.topic'),
        ),
        migrations.AddField(
            model_name='like',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postModule_like_related', related_query_name='postModule_likes', to='postModule.post'),
        ),
        migrations.AddField(
            model_name='like',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_like_related', related_query_name='social_likes', to='social.profil'),
        ),
    ]
