# Generated by Django 3.2.9 on 2021-12-07 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postModule', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
